# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5cd234166414574af4e44a00fbb4ec396601b4a7b7c3e81a44ddc5de89402ae17b1e5db0b2d46d2b3c1614a4bfd7069a1e2013e7318c2c101a9a93016ce49cae

test:
  secret_key_base: 4ae2f779be654e806fd754847f76c348a01c2ec031d4c975abd28438b50c2ffcabf03a7fc988885c9302fd58bdd26bcb8e6419dcc5b7851596cdeb6454109be3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
